# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiac', '0003_auto_20160121_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrm',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
