# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiac', '0003_auto_20160129_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='average',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='maxim',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='minim',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
