# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 17:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cardiac', '0004_auto_20160129_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 29, 17, 49, 58, 449262, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
