# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiac', '0007_hrm_vfc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health',
            old_name='average',
            new_name='averagehr',
        ),
        migrations.RenameField(
            model_name='hrm',
            old_name='vfc',
            new_name='hrv',
        ),
        migrations.AddField(
            model_name='health',
            name='averagehrv',
            field=models.IntegerField(null=True),
        ),
    ]
