# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardiac', '0008_auto_20160415_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrm',
            name='state',
        ),
    ]
