# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardiac', '0009_remove_hrm_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='health',
            name='main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cardiac.Main'),
        ),
    ]
