# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-05 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiac', '0012_auto_20160525_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='datend',
            field=models.DateTimeField(null=True),
        ),
    ]
